/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gobgp_pb = require('./gobgp_pb.js');
goog.exportSymbol('proto.gobgpapi.AddPathCapability', null, global);
goog.exportSymbol('proto.gobgpapi.AddPathCapabilityTuple', null, global);
goog.exportSymbol('proto.gobgpapi.AddPathMode', null, global);
goog.exportSymbol('proto.gobgpapi.CarryingLabelInfoCapability', null, global);
goog.exportSymbol('proto.gobgpapi.EnhancedRouteRefreshCapability', null, global);
goog.exportSymbol('proto.gobgpapi.ExtendedNexthopCapability', null, global);
goog.exportSymbol('proto.gobgpapi.ExtendedNexthopCapabilityTuple', null, global);
goog.exportSymbol('proto.gobgpapi.FourOctetASNumberCapability', null, global);
goog.exportSymbol('proto.gobgpapi.GracefulRestartCapability', null, global);
goog.exportSymbol('proto.gobgpapi.GracefulRestartCapabilityTuple', null, global);
goog.exportSymbol('proto.gobgpapi.LongLivedGracefulRestartCapability', null, global);
goog.exportSymbol('proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple', null, global);
goog.exportSymbol('proto.gobgpapi.MultiProtocolCapability', null, global);
goog.exportSymbol('proto.gobgpapi.RouteRefreshCapability', null, global);
goog.exportSymbol('proto.gobgpapi.RouteRefreshCiscoCapability', null, global);
goog.exportSymbol('proto.gobgpapi.UnknownCapability', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.MultiProtocolCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.MultiProtocolCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.MultiProtocolCapability.displayName = 'proto.gobgpapi.MultiProtocolCapability';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.MultiProtocolCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.MultiProtocolCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.MultiProtocolCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.MultiProtocolCapability.toObject = function(includeInstance, msg) {
  var f, obj = {
    family: (f = msg.getFamily()) && gobgp_pb.Family.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.MultiProtocolCapability}
 */
proto.gobgpapi.MultiProtocolCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.MultiProtocolCapability;
  return proto.gobgpapi.MultiProtocolCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.MultiProtocolCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.MultiProtocolCapability}
 */
proto.gobgpapi.MultiProtocolCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gobgp_pb.Family;
      reader.readMessage(value,gobgp_pb.Family.deserializeBinaryFromReader);
      msg.setFamily(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.MultiProtocolCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.MultiProtocolCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.MultiProtocolCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.MultiProtocolCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFamily();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gobgp_pb.Family.serializeBinaryToWriter
    );
  }
};


/**
 * optional Family family = 1;
 * @return {?proto.gobgpapi.Family}
 */
proto.gobgpapi.MultiProtocolCapability.prototype.getFamily = function() {
  return /** @type{?proto.gobgpapi.Family} */ (
    jspb.Message.getWrapperField(this, gobgp_pb.Family, 1));
};


/** @param {?proto.gobgpapi.Family|undefined} value */
proto.gobgpapi.MultiProtocolCapability.prototype.setFamily = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gobgpapi.MultiProtocolCapability.prototype.clearFamily = function() {
  this.setFamily(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gobgpapi.MultiProtocolCapability.prototype.hasFamily = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.RouteRefreshCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.RouteRefreshCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.RouteRefreshCapability.displayName = 'proto.gobgpapi.RouteRefreshCapability';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.RouteRefreshCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.RouteRefreshCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.RouteRefreshCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.RouteRefreshCapability.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.RouteRefreshCapability}
 */
proto.gobgpapi.RouteRefreshCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.RouteRefreshCapability;
  return proto.gobgpapi.RouteRefreshCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.RouteRefreshCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.RouteRefreshCapability}
 */
proto.gobgpapi.RouteRefreshCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.RouteRefreshCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.RouteRefreshCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.RouteRefreshCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.RouteRefreshCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.CarryingLabelInfoCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.CarryingLabelInfoCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.CarryingLabelInfoCapability.displayName = 'proto.gobgpapi.CarryingLabelInfoCapability';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.CarryingLabelInfoCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.CarryingLabelInfoCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.CarryingLabelInfoCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.CarryingLabelInfoCapability.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.CarryingLabelInfoCapability}
 */
proto.gobgpapi.CarryingLabelInfoCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.CarryingLabelInfoCapability;
  return proto.gobgpapi.CarryingLabelInfoCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.CarryingLabelInfoCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.CarryingLabelInfoCapability}
 */
proto.gobgpapi.CarryingLabelInfoCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.CarryingLabelInfoCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.CarryingLabelInfoCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.CarryingLabelInfoCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.CarryingLabelInfoCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.ExtendedNexthopCapabilityTuple, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.ExtendedNexthopCapabilityTuple.displayName = 'proto.gobgpapi.ExtendedNexthopCapabilityTuple';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.ExtendedNexthopCapabilityTuple.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.ExtendedNexthopCapabilityTuple} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.toObject = function(includeInstance, msg) {
  var f, obj = {
    nlriFamily: (f = msg.getNlriFamily()) && gobgp_pb.Family.toObject(includeInstance, f),
    nexthopFamily: (f = msg.getNexthopFamily()) && gobgp_pb.Family.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.ExtendedNexthopCapabilityTuple}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.ExtendedNexthopCapabilityTuple;
  return proto.gobgpapi.ExtendedNexthopCapabilityTuple.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.ExtendedNexthopCapabilityTuple} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.ExtendedNexthopCapabilityTuple}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gobgp_pb.Family;
      reader.readMessage(value,gobgp_pb.Family.deserializeBinaryFromReader);
      msg.setNlriFamily(value);
      break;
    case 2:
      var value = new gobgp_pb.Family;
      reader.readMessage(value,gobgp_pb.Family.deserializeBinaryFromReader);
      msg.setNexthopFamily(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.ExtendedNexthopCapabilityTuple.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.ExtendedNexthopCapabilityTuple} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNlriFamily();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gobgp_pb.Family.serializeBinaryToWriter
    );
  }
  f = message.getNexthopFamily();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      gobgp_pb.Family.serializeBinaryToWriter
    );
  }
};


/**
 * optional Family nlri_family = 1;
 * @return {?proto.gobgpapi.Family}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.getNlriFamily = function() {
  return /** @type{?proto.gobgpapi.Family} */ (
    jspb.Message.getWrapperField(this, gobgp_pb.Family, 1));
};


/** @param {?proto.gobgpapi.Family|undefined} value */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.setNlriFamily = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.clearNlriFamily = function() {
  this.setNlriFamily(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.hasNlriFamily = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Family nexthop_family = 2;
 * @return {?proto.gobgpapi.Family}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.getNexthopFamily = function() {
  return /** @type{?proto.gobgpapi.Family} */ (
    jspb.Message.getWrapperField(this, gobgp_pb.Family, 2));
};


/** @param {?proto.gobgpapi.Family|undefined} value */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.setNexthopFamily = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.clearNexthopFamily = function() {
  this.setNexthopFamily(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gobgpapi.ExtendedNexthopCapabilityTuple.prototype.hasNexthopFamily = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.ExtendedNexthopCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gobgpapi.ExtendedNexthopCapability.repeatedFields_, null);
};
goog.inherits(proto.gobgpapi.ExtendedNexthopCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.ExtendedNexthopCapability.displayName = 'proto.gobgpapi.ExtendedNexthopCapability';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gobgpapi.ExtendedNexthopCapability.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.ExtendedNexthopCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.ExtendedNexthopCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.ExtendedNexthopCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.ExtendedNexthopCapability.toObject = function(includeInstance, msg) {
  var f, obj = {
    tuplesList: jspb.Message.toObjectList(msg.getTuplesList(),
    proto.gobgpapi.ExtendedNexthopCapabilityTuple.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.ExtendedNexthopCapability}
 */
proto.gobgpapi.ExtendedNexthopCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.ExtendedNexthopCapability;
  return proto.gobgpapi.ExtendedNexthopCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.ExtendedNexthopCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.ExtendedNexthopCapability}
 */
proto.gobgpapi.ExtendedNexthopCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gobgpapi.ExtendedNexthopCapabilityTuple;
      reader.readMessage(value,proto.gobgpapi.ExtendedNexthopCapabilityTuple.deserializeBinaryFromReader);
      msg.addTuples(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.ExtendedNexthopCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.ExtendedNexthopCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.ExtendedNexthopCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.ExtendedNexthopCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTuplesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.gobgpapi.ExtendedNexthopCapabilityTuple.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ExtendedNexthopCapabilityTuple tuples = 1;
 * @return {!Array.<!proto.gobgpapi.ExtendedNexthopCapabilityTuple>}
 */
proto.gobgpapi.ExtendedNexthopCapability.prototype.getTuplesList = function() {
  return /** @type{!Array.<!proto.gobgpapi.ExtendedNexthopCapabilityTuple>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gobgpapi.ExtendedNexthopCapabilityTuple, 1));
};


/** @param {!Array.<!proto.gobgpapi.ExtendedNexthopCapabilityTuple>} value */
proto.gobgpapi.ExtendedNexthopCapability.prototype.setTuplesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gobgpapi.ExtendedNexthopCapabilityTuple=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gobgpapi.ExtendedNexthopCapabilityTuple}
 */
proto.gobgpapi.ExtendedNexthopCapability.prototype.addTuples = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gobgpapi.ExtendedNexthopCapabilityTuple, opt_index);
};


proto.gobgpapi.ExtendedNexthopCapability.prototype.clearTuplesList = function() {
  this.setTuplesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.GracefulRestartCapabilityTuple = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.GracefulRestartCapabilityTuple, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.GracefulRestartCapabilityTuple.displayName = 'proto.gobgpapi.GracefulRestartCapabilityTuple';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.GracefulRestartCapabilityTuple.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.GracefulRestartCapabilityTuple} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.toObject = function(includeInstance, msg) {
  var f, obj = {
    family: (f = msg.getFamily()) && gobgp_pb.Family.toObject(includeInstance, f),
    flags: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.GracefulRestartCapabilityTuple}
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.GracefulRestartCapabilityTuple;
  return proto.gobgpapi.GracefulRestartCapabilityTuple.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.GracefulRestartCapabilityTuple} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.GracefulRestartCapabilityTuple}
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gobgp_pb.Family;
      reader.readMessage(value,gobgp_pb.Family.deserializeBinaryFromReader);
      msg.setFamily(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFlags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.GracefulRestartCapabilityTuple.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.GracefulRestartCapabilityTuple} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFamily();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gobgp_pb.Family.serializeBinaryToWriter
    );
  }
  f = message.getFlags();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional Family family = 1;
 * @return {?proto.gobgpapi.Family}
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.getFamily = function() {
  return /** @type{?proto.gobgpapi.Family} */ (
    jspb.Message.getWrapperField(this, gobgp_pb.Family, 1));
};


/** @param {?proto.gobgpapi.Family|undefined} value */
proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.setFamily = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.clearFamily = function() {
  this.setFamily(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.hasFamily = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 flags = 2;
 * @return {number}
 */
proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.getFlags = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.gobgpapi.GracefulRestartCapabilityTuple.prototype.setFlags = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.GracefulRestartCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gobgpapi.GracefulRestartCapability.repeatedFields_, null);
};
goog.inherits(proto.gobgpapi.GracefulRestartCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.GracefulRestartCapability.displayName = 'proto.gobgpapi.GracefulRestartCapability';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gobgpapi.GracefulRestartCapability.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.GracefulRestartCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.GracefulRestartCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.GracefulRestartCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.GracefulRestartCapability.toObject = function(includeInstance, msg) {
  var f, obj = {
    flags: jspb.Message.getFieldWithDefault(msg, 1, 0),
    time: jspb.Message.getFieldWithDefault(msg, 2, 0),
    tuplesList: jspb.Message.toObjectList(msg.getTuplesList(),
    proto.gobgpapi.GracefulRestartCapabilityTuple.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.GracefulRestartCapability}
 */
proto.gobgpapi.GracefulRestartCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.GracefulRestartCapability;
  return proto.gobgpapi.GracefulRestartCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.GracefulRestartCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.GracefulRestartCapability}
 */
proto.gobgpapi.GracefulRestartCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFlags(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTime(value);
      break;
    case 3:
      var value = new proto.gobgpapi.GracefulRestartCapabilityTuple;
      reader.readMessage(value,proto.gobgpapi.GracefulRestartCapabilityTuple.deserializeBinaryFromReader);
      msg.addTuples(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.GracefulRestartCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.GracefulRestartCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.GracefulRestartCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.GracefulRestartCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlags();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getTuplesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.gobgpapi.GracefulRestartCapabilityTuple.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 flags = 1;
 * @return {number}
 */
proto.gobgpapi.GracefulRestartCapability.prototype.getFlags = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.gobgpapi.GracefulRestartCapability.prototype.setFlags = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 time = 2;
 * @return {number}
 */
proto.gobgpapi.GracefulRestartCapability.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.gobgpapi.GracefulRestartCapability.prototype.setTime = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated GracefulRestartCapabilityTuple tuples = 3;
 * @return {!Array.<!proto.gobgpapi.GracefulRestartCapabilityTuple>}
 */
proto.gobgpapi.GracefulRestartCapability.prototype.getTuplesList = function() {
  return /** @type{!Array.<!proto.gobgpapi.GracefulRestartCapabilityTuple>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gobgpapi.GracefulRestartCapabilityTuple, 3));
};


/** @param {!Array.<!proto.gobgpapi.GracefulRestartCapabilityTuple>} value */
proto.gobgpapi.GracefulRestartCapability.prototype.setTuplesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.gobgpapi.GracefulRestartCapabilityTuple=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gobgpapi.GracefulRestartCapabilityTuple}
 */
proto.gobgpapi.GracefulRestartCapability.prototype.addTuples = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.gobgpapi.GracefulRestartCapabilityTuple, opt_index);
};


proto.gobgpapi.GracefulRestartCapability.prototype.clearTuplesList = function() {
  this.setTuplesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.FourOctetASNumberCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.FourOctetASNumberCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.FourOctetASNumberCapability.displayName = 'proto.gobgpapi.FourOctetASNumberCapability';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.FourOctetASNumberCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.FourOctetASNumberCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.FourOctetASNumberCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.FourOctetASNumberCapability.toObject = function(includeInstance, msg) {
  var f, obj = {
    as: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.FourOctetASNumberCapability}
 */
proto.gobgpapi.FourOctetASNumberCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.FourOctetASNumberCapability;
  return proto.gobgpapi.FourOctetASNumberCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.FourOctetASNumberCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.FourOctetASNumberCapability}
 */
proto.gobgpapi.FourOctetASNumberCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.FourOctetASNumberCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.FourOctetASNumberCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.FourOctetASNumberCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.FourOctetASNumberCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAs();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
};


/**
 * optional uint32 as = 1;
 * @return {number}
 */
proto.gobgpapi.FourOctetASNumberCapability.prototype.getAs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.gobgpapi.FourOctetASNumberCapability.prototype.setAs = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.AddPathCapabilityTuple = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.AddPathCapabilityTuple, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.AddPathCapabilityTuple.displayName = 'proto.gobgpapi.AddPathCapabilityTuple';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.AddPathCapabilityTuple.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.AddPathCapabilityTuple.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.AddPathCapabilityTuple} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.AddPathCapabilityTuple.toObject = function(includeInstance, msg) {
  var f, obj = {
    family: (f = msg.getFamily()) && gobgp_pb.Family.toObject(includeInstance, f),
    mode: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.AddPathCapabilityTuple}
 */
proto.gobgpapi.AddPathCapabilityTuple.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.AddPathCapabilityTuple;
  return proto.gobgpapi.AddPathCapabilityTuple.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.AddPathCapabilityTuple} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.AddPathCapabilityTuple}
 */
proto.gobgpapi.AddPathCapabilityTuple.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gobgp_pb.Family;
      reader.readMessage(value,gobgp_pb.Family.deserializeBinaryFromReader);
      msg.setFamily(value);
      break;
    case 2:
      var value = /** @type {!proto.gobgpapi.AddPathMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.AddPathCapabilityTuple.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.AddPathCapabilityTuple.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.AddPathCapabilityTuple} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.AddPathCapabilityTuple.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFamily();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gobgp_pb.Family.serializeBinaryToWriter
    );
  }
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional Family family = 1;
 * @return {?proto.gobgpapi.Family}
 */
proto.gobgpapi.AddPathCapabilityTuple.prototype.getFamily = function() {
  return /** @type{?proto.gobgpapi.Family} */ (
    jspb.Message.getWrapperField(this, gobgp_pb.Family, 1));
};


/** @param {?proto.gobgpapi.Family|undefined} value */
proto.gobgpapi.AddPathCapabilityTuple.prototype.setFamily = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gobgpapi.AddPathCapabilityTuple.prototype.clearFamily = function() {
  this.setFamily(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gobgpapi.AddPathCapabilityTuple.prototype.hasFamily = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AddPathMode mode = 2;
 * @return {!proto.gobgpapi.AddPathMode}
 */
proto.gobgpapi.AddPathCapabilityTuple.prototype.getMode = function() {
  return /** @type {!proto.gobgpapi.AddPathMode} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.gobgpapi.AddPathMode} value */
proto.gobgpapi.AddPathCapabilityTuple.prototype.setMode = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.AddPathCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gobgpapi.AddPathCapability.repeatedFields_, null);
};
goog.inherits(proto.gobgpapi.AddPathCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.AddPathCapability.displayName = 'proto.gobgpapi.AddPathCapability';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gobgpapi.AddPathCapability.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.AddPathCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.AddPathCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.AddPathCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.AddPathCapability.toObject = function(includeInstance, msg) {
  var f, obj = {
    tuplesList: jspb.Message.toObjectList(msg.getTuplesList(),
    proto.gobgpapi.AddPathCapabilityTuple.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.AddPathCapability}
 */
proto.gobgpapi.AddPathCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.AddPathCapability;
  return proto.gobgpapi.AddPathCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.AddPathCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.AddPathCapability}
 */
proto.gobgpapi.AddPathCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gobgpapi.AddPathCapabilityTuple;
      reader.readMessage(value,proto.gobgpapi.AddPathCapabilityTuple.deserializeBinaryFromReader);
      msg.addTuples(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.AddPathCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.AddPathCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.AddPathCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.AddPathCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTuplesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.gobgpapi.AddPathCapabilityTuple.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AddPathCapabilityTuple tuples = 1;
 * @return {!Array.<!proto.gobgpapi.AddPathCapabilityTuple>}
 */
proto.gobgpapi.AddPathCapability.prototype.getTuplesList = function() {
  return /** @type{!Array.<!proto.gobgpapi.AddPathCapabilityTuple>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gobgpapi.AddPathCapabilityTuple, 1));
};


/** @param {!Array.<!proto.gobgpapi.AddPathCapabilityTuple>} value */
proto.gobgpapi.AddPathCapability.prototype.setTuplesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gobgpapi.AddPathCapabilityTuple=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gobgpapi.AddPathCapabilityTuple}
 */
proto.gobgpapi.AddPathCapability.prototype.addTuples = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gobgpapi.AddPathCapabilityTuple, opt_index);
};


proto.gobgpapi.AddPathCapability.prototype.clearTuplesList = function() {
  this.setTuplesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.EnhancedRouteRefreshCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.EnhancedRouteRefreshCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.EnhancedRouteRefreshCapability.displayName = 'proto.gobgpapi.EnhancedRouteRefreshCapability';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.EnhancedRouteRefreshCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.EnhancedRouteRefreshCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.EnhancedRouteRefreshCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.EnhancedRouteRefreshCapability.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.EnhancedRouteRefreshCapability}
 */
proto.gobgpapi.EnhancedRouteRefreshCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.EnhancedRouteRefreshCapability;
  return proto.gobgpapi.EnhancedRouteRefreshCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.EnhancedRouteRefreshCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.EnhancedRouteRefreshCapability}
 */
proto.gobgpapi.EnhancedRouteRefreshCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.EnhancedRouteRefreshCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.EnhancedRouteRefreshCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.EnhancedRouteRefreshCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.EnhancedRouteRefreshCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.displayName = 'proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.toObject = function(includeInstance, msg) {
  var f, obj = {
    family: (f = msg.getFamily()) && gobgp_pb.Family.toObject(includeInstance, f),
    flags: jspb.Message.getFieldWithDefault(msg, 2, 0),
    time: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple;
  return proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gobgp_pb.Family;
      reader.readMessage(value,gobgp_pb.Family.deserializeBinaryFromReader);
      msg.setFamily(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFlags(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFamily();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gobgp_pb.Family.serializeBinaryToWriter
    );
  }
  f = message.getFlags();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional Family family = 1;
 * @return {?proto.gobgpapi.Family}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.getFamily = function() {
  return /** @type{?proto.gobgpapi.Family} */ (
    jspb.Message.getWrapperField(this, gobgp_pb.Family, 1));
};


/** @param {?proto.gobgpapi.Family|undefined} value */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.setFamily = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.clearFamily = function() {
  this.setFamily(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.hasFamily = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 flags = 2;
 * @return {number}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.getFlags = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.setFlags = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 time = 3;
 * @return {number}
 */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.prototype.setTime = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.LongLivedGracefulRestartCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gobgpapi.LongLivedGracefulRestartCapability.repeatedFields_, null);
};
goog.inherits(proto.gobgpapi.LongLivedGracefulRestartCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.LongLivedGracefulRestartCapability.displayName = 'proto.gobgpapi.LongLivedGracefulRestartCapability';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.LongLivedGracefulRestartCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.LongLivedGracefulRestartCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.toObject = function(includeInstance, msg) {
  var f, obj = {
    tuplesList: jspb.Message.toObjectList(msg.getTuplesList(),
    proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.LongLivedGracefulRestartCapability}
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.LongLivedGracefulRestartCapability;
  return proto.gobgpapi.LongLivedGracefulRestartCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.LongLivedGracefulRestartCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.LongLivedGracefulRestartCapability}
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple;
      reader.readMessage(value,proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.deserializeBinaryFromReader);
      msg.addTuples(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.LongLivedGracefulRestartCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.LongLivedGracefulRestartCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTuplesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple.serializeBinaryToWriter
    );
  }
};


/**
 * repeated LongLivedGracefulRestartCapabilityTuple tuples = 1;
 * @return {!Array.<!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple>}
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.prototype.getTuplesList = function() {
  return /** @type{!Array.<!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple, 1));
};


/** @param {!Array.<!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple>} value */
proto.gobgpapi.LongLivedGracefulRestartCapability.prototype.setTuplesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple}
 */
proto.gobgpapi.LongLivedGracefulRestartCapability.prototype.addTuples = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gobgpapi.LongLivedGracefulRestartCapabilityTuple, opt_index);
};


proto.gobgpapi.LongLivedGracefulRestartCapability.prototype.clearTuplesList = function() {
  this.setTuplesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.RouteRefreshCiscoCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.RouteRefreshCiscoCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.RouteRefreshCiscoCapability.displayName = 'proto.gobgpapi.RouteRefreshCiscoCapability';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.RouteRefreshCiscoCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.RouteRefreshCiscoCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.RouteRefreshCiscoCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.RouteRefreshCiscoCapability.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.RouteRefreshCiscoCapability}
 */
proto.gobgpapi.RouteRefreshCiscoCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.RouteRefreshCiscoCapability;
  return proto.gobgpapi.RouteRefreshCiscoCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.RouteRefreshCiscoCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.RouteRefreshCiscoCapability}
 */
proto.gobgpapi.RouteRefreshCiscoCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.RouteRefreshCiscoCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.RouteRefreshCiscoCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.RouteRefreshCiscoCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.RouteRefreshCiscoCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gobgpapi.UnknownCapability = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gobgpapi.UnknownCapability, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gobgpapi.UnknownCapability.displayName = 'proto.gobgpapi.UnknownCapability';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gobgpapi.UnknownCapability.prototype.toObject = function(opt_includeInstance) {
  return proto.gobgpapi.UnknownCapability.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gobgpapi.UnknownCapability} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.UnknownCapability.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: msg.getValue_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gobgpapi.UnknownCapability}
 */
proto.gobgpapi.UnknownCapability.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gobgpapi.UnknownCapability;
  return proto.gobgpapi.UnknownCapability.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gobgpapi.UnknownCapability} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gobgpapi.UnknownCapability}
 */
proto.gobgpapi.UnknownCapability.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gobgpapi.UnknownCapability.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gobgpapi.UnknownCapability.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gobgpapi.UnknownCapability} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gobgpapi.UnknownCapability.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getValue_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional uint32 code = 1;
 * @return {number}
 */
proto.gobgpapi.UnknownCapability.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.gobgpapi.UnknownCapability.prototype.setCode = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes value = 2;
 * @return {string}
 */
proto.gobgpapi.UnknownCapability.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes value = 2;
 * This is a type-conversion wrapper around `getValue()`
 * @return {string}
 */
proto.gobgpapi.UnknownCapability.prototype.getValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getValue()));
};


/**
 * optional bytes value = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getValue()`
 * @return {!Uint8Array}
 */
proto.gobgpapi.UnknownCapability.prototype.getValue_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getValue()));
};


/** @param {!(string|Uint8Array)} value */
proto.gobgpapi.UnknownCapability.prototype.setValue = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.gobgpapi.AddPathMode = {
  MODE_NONE: 0,
  MODE_RECEIVE: 1,
  MODE_SEND: 2,
  MODE_BOTH: 3
};

goog.object.extend(exports, proto.gobgpapi);
